### ISSUE TITLE
It wont launch on startup.

### ISSUE THREAD

**Issue by Vahryx** [Ilshidur/LoL-item-sets#9]
I have it ticked in the program. I have the program run as administrator. I have also put a shortcut to the exe in the startup folder. However, it never launches. Any ideas?

**Comment by Ilshidur** [comment]
Thanks for your report.
What is your operating system ?

**Comment by Vahryx** [comment]
I run Windows 7 Home Premium (64 bit)

**Comment by Ilshidur** [comment]
Check your registry if the following exists for this application : `SOFTWARE\Microsoft\Windows\CurrentVersion\Run`.

Sorry, but at the moment I don't have access to a Windows 7 installation to reproduce the bug.

**Comment by Vahryx** [comment]
Okay, there is no entry for it there. Would I just create a new string value with the value "C:\Users\#USER#\Documents\LoL-item-sets-0.3.0\LoL item sets.exe"?

Just to make sure, the name of the value doesn't matter right?

**Comment by Ilshidur** [comment]
The name of the value must be the full path of the application, so yes, it matters.
Make sure to create it for the "current user" (only you).

I tried to fix this problem [here](https://github.com/Ilshidur/LoL-item-sets/pull/10) and will investigate this.

**Comment by Vahryx** [comment]
Oops. I was looking for the registry key under local machine, not current user. There IS actually a registry key there for LoL-item-sets-generator with the correct path to the exe.

Sorry about that!

**Comment by Ilshidur** [comment]
Is the path correct ?
Does it begin with a disk letter like `C:\` ?

**Comment by Vahryx** [comment]
Yes.
The path is : `C:\Users\Vahryx\Documents\LoL-item-sets-0.3.0\`
Within this folder is my "Lol item sets.exe"

Could the problem be that the path does not include the exe.

For example should it be : `C:\Users\Vahryx\Documents\LoL-item-sets-0.3.0\Lol item sets.exe`
Rather than : `C:\Users\Vahryx\Documents\LoL-item-sets-0.3.0\`

**Comment by Ilshidur** [comment]
O.K. This is what I thought. The key does not contain the .exe file, so the app won't run on Windows startup.

Try to replace the key to the one you suggested. You should be able to see the app running after a restart.

This issue will definitely be fixed in the version 0.3.1.

**Comment by Vahryx** [comment]
Hmm. It is still not launching on startup.

Here is a screenshot of my `regedit` window. The path is correct.
![regedit](https://cloud.githubusercontent.com/assets/22270252/25169383/f9146ba8-2525-11e7-88ac-005c0c35ccf0.png)

And here is a screenshot of my `Documents` folder just to show I'm not spelling it incorrectly.
![the exe](https://cloud.githubusercontent.com/assets/22270252/25169386/fa21e52a-2525-11e7-915c-624f5ff2ba92.png)

Any ideas?

**Comment by Ilshidur** [comment]
Have you checked the "Run as administrator" checkbox in the app properties ? (right clic > "Properties").

If the registry key `HKey_Current_User\Software\Microsoft\Windows\CurrentVersion\Run` doesn't work, try with `HKLM\Software\Microsoft\Windows\CurrentVersion\Run` (local machine). I think this should work.

**Comment by Vahryx** [comment]
"Run as administrator" is ticked.
![properties](https://cloud.githubusercontent.com/assets/22270252/25172017/eca7be70-252e-11e7-833a-44953d8c4cce.png)

And I created another registry key in HKEY_LOCAL_MACHINE.
![regedit2](https://cloud.githubusercontent.com/assets/22270252/25172109/2ac9ea16-252f-11e7-9808-c7c1a6dfe64b.png)

Still not working. Doesn't make sense to me.

**Comment by Ilshidur** [comment]
What a wierd behavior.

Maybe try to put quotes (`"`) like `"C:\Users\Jack\Documents\LoL-item-sets-0.3.0\LoL item sets.exe"` for both keys (local machine and current user).

**Comment by Vahryx** [comment]
Still not working.

**Comment by Vahryx** [comment]
I also made sure that they were **ticked** under "Services" in `msconfig.exe`

**Comment by Vahryx** [comment]
Maybe my computer is the problem.

I just created a Scheduled Task for the application and it works fine.

**Comment by Ilshidur** [comment]
When you added the key in your registry, did your app showed "Launch on Windows start" as checked ?

Or maybe the app itself is the problem.
I think you can try to register a key with an other app name (a random .exe file) and see if it runs when you restart.

**Comment by Vahryx** [comment]
"Launch on Windows start" was checked, yes.

I just tried adding a key in HKEY_CURRENT_USER for another .exe and it did indeed run when I restarted.

**Comment by Ilshidur** [comment]
This means that the app has successfully read the registry.

Either :
* the path does not allow spaces in the name (if your .exe had no spaces in its path)
* or the app won't run on startup because it needs administrator rights (meaning that the app will need to use Scheduled Tasks)
* according to [this](http://stackoverflow.com/questions/9544454/regedit-to-run-an-exe-at-startup-as-administrator), you probably have a `HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Run` registry folder where you must insert the key

Otherwise, I can't really help you. I'll investigate myself as soon as I get a Windows 7 installation.

**Comment by Vahryx** [comment]
Thanks for all the help! I really appreciate it.
